version: 2.1

jobs:
  setup:
    docker:
      - image: cimg/node:19.5.0

    steps:
      - checkout

      - restore_cache:
          key: pnpm-cache-v1-{{ checksum "pnpm-lock.yml" }}

      - run:
          name: 'Install dependencies'
          command: pnpm install

      - save_cache:
          key: pnpm-cache-v1-{{ checksum "pnpm-lock.yml" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: .
          paths:
            - ./*

  build:
    docker:
      - image: cimg/node:19.5.0

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: 'Build app and nuxt'
          command: pnpm build

      - persist_to_workspace:
          root: .
          paths:
            - ./*

  lint:
    docker:
      - image: cimg/node:19.5.0

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: 'Verify code quality and formatting'
          command: pnpm lint

  test:
    docker:
      - image: cimg/node:19.5.0

    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: 'Run unit tests'
          command: pnpm test

  e2e:
    docker:
       - image: mcr.microsoft.com/playwright:v1.30.0-focal

    steps:
      - checkout

      - run:
          name: Install
          command: pnpm i -D @playwright/test && npx playwright install --with-deps

      - run:
          name: Start playground local development server
          command: pnpm dev
          background: true

      - run:
          name: Run integration tests
          command: pnpm e2e

workflows:
  test-and-build:
    jobs:
      - setup:
          context: readonly-github-packages

      - build:
          requires:
            - setup

      - lint:
          requires:
            - build

      - test:
          requires:
            - build

      - e2e:
          requires:
            - build
